version: '3.8'

services:
  app:
    image: ghcr.io/caoduyen01101997/micromaut:latest
    container_name: micromaut-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: pass123
    extra_hosts:
      - "host.docker.internal:host-gateway"
