
micronaut:
  application:
    name: micromaut
  server:
    port: 8080
netty:
  default:
    allocator:
      max-order: 3
mongodb:
    uri: mongodb://localhost:27017/coffee
datasources:
  default:
    url: jdbc:postgresql://103.245.237.151:5432/mydatabase
    driverClassName: org.postgresql.Driver
    username: myuser
    password: pass123
jpa:
  default:
    entity-scan:
      packages: 'com.example'


