
micronaut:
  application:
    name: micromaut
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        default:
          allowedOrigins:
            - http://localhost:4200
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
          allowedHeaders:
            - '*'
          exposedHeaders:
            - '*'
          allowCredentials: true
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
        path: /login
        post:
          enabled: true
    intercept-url-map:
      - pattern: /login
        http-method: POST
        access: isAnonymous()
      - pattern: /account/**
        access: isAnonymous()
      - pattern: /**
        access: isAuthenticated()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
netty:
  default:
    allocator:
      max-order: 3
mongodb:
    uri: mongodb://localhost:27017/coffee
datasources:
  default:
    url: jdbc:postgresql://157.10.53.34:5432/mydatabase
    driverClassName: org.postgresql.Driver
    username: myuser
    password: pass123
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jpa:
  default:
    entity-scan:
      packages: 'com.example'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
logger:
  levels:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    io.micronaut.security: DEBUG
    com.example.provider.CustomAuthenticationProvider: DEBUG
    io.micronaut.web.router: TRACE
    io.micronaut.security.filters: TRACE
    io.micronaut.security.token: TRACE

